name: Trigger auto deployment for maggiehou-external

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/maggiehou-external-AutoDeployTrigger-8e87cc7c-7f0f-4c1e-90b9-0330b2b27f2b.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MAGGIEHOUEXTERNAL_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: maggiecustom.azurecr.io
          registryUsername: ${{ secrets.MAGGIEHOUEXTERNAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAGGIEHOUEXTERNAL_REGISTRY_PASSWORD }}
          containerAppName: maggiehou-external
          resourceGroup: maggiehou-containerappgroup
          imageToBuild: maggiecustom.azurecr.io/maggiehou-external:${{ github.sha }}
          

     

